---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: parent
  create: all
  templates:
  - page
- type: jekyll-pages
  label: children
  create: all
  templates:
  - children-page
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - page
- type: document
  path: index.md
  label: Home
- type: document
  path: README.md
  label: README
  read_only: true
upload_dir: assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - UNIFORM_API_KEY=uf1w9l4c3zdg4fjf9jjhzrpsccn4eqwmdjegtcm5hshyp9pv940ka96mk63gx693r0pxwkmpncjur50n2sgvujs38svevx79c
    UNIFORM_PROJECT_ID=ff410d04-d594-4b77-a987-5256d3749805 CONTENTFUL_SPACE_ID=9i6monomvi82
    CONTENTFUL_ENVIRONMENT=master GA_UA_ID=UA-225469170-1=
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
